### ISSUE TITLE
Simulation ended due to 'Distance between bonded neighbor error'

### ISSUE THREAD

**Issue by Prateek1410** [sulcgroup/oxdna-web#27]
Greetings everyone,

I submitted a job for 1E10 steps at Print conf interval of 5E5 and print energy every at 5E4. The job only ran for 1E7 steps and it seems it ended due to the error, 'Distance between bonded neighbors 4693 and 4694 exceeds acceptable values (d = 1708.595703'. Also, no last configuration has been generated. This occurred perhaps because one particle (C 0:4:4694) got isolated from the rest of the system and thus, its bonds are stretched causing that error. 

Prior to this, the log file also noted that, 'Fix diffusion went too far' and 'Fix diffusion hopeless'. I don't know if that's of significance. The file in question is:

Htopbottom5E5PCI; **c35a7adf-eb73-42de-862d-29f664297184**

Could you please help me understand this? Thank you so much for your time and consideration. 

Warm regards,
Prateek

**Comment by ErikPoppleton** [comment]
Hi Prateek,

Your structure exploded during relaxation.  As you noted, particle 4694 appears to have encountered an excluded volume clash with another particle.  The simulation will not start if there are stretched bonds as they will cause the whole system to instantly explode due to the potential energy.  I would recommend re-doing the relaxation and decreasing the MD dt in "Relaxation Parameters" by a factor of 10 to make the process more gentle.

If you have not yet done so, I highly recommend reading [this paper](https://arxiv.org/abs/2004.05052) for an overview on how to relax structures.  Also, looking at your structure, I have relaxed structures similar to that before and you may also benefit from pulling the arms apart and doing some RBD in oxView before starting the simulation.  This will ensure that the arms do not collide, which appears to have been the source of the explosion in this simulation.  See [this example](https://github.com/sulcgroup/oxdna-viewer/blob/master/examples/square/README.md) for clustering and RBD instructions.  In your case you will have to manually assign the clusters with the box selector because there is not enough separation in the hinge region for the automatic clusterer to detect.

Side note, 1e10 steps will not complete within the 4-day allotted time and so your trajectory will not be compressed at the end of the run, making it take quite a bit longer for you to download at the end.  If I may ask, what are you doing that you require such long timescales?  It sounds like you might be doing something that could benefit from enhanced sampling methods.

Erik

**Comment by Prateek1410** [comment]
Hi Erik! 

Sorry for the late response but just wanted to thank you for the extensive help. I have been working on all the pointers you shared. No particular reason for the long timescales, I am afraid. I am a novice in the simulation field so I was just experimenting around, trying to form an understanding. Your comments have been instrumental in this regard; thanks again!

Best Wishes,
Prateek
